/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'

// Create Virtual Routes

const DashboardSettingsRouteLazyImport = createFileRoute(
  '/dashboard/settings',
)()
const DashboardUsersIndexLazyImport = createFileRoute('/dashboard/users/')()
const DashboardStatisticsIndexLazyImport = createFileRoute(
  '/dashboard/statistics/',
)()
const DashboardSettingsIndexLazyImport = createFileRoute(
  '/dashboard/settings/',
)()
const DashboardNotificationsIndexLazyImport = createFileRoute(
  '/dashboard/notifications/',
)()
const DashboardLevelTwoIndexLazyImport = createFileRoute(
  '/dashboard/level-two/',
)()
const DashboardLevelOneIndexLazyImport = createFileRoute(
  '/dashboard/level-one/',
)()
const DashboardSettingsWalletLazyImport = createFileRoute(
  '/dashboard/settings/wallet',
)()

// Create/Update Routes

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardSettingsRouteLazyRoute = DashboardSettingsRouteLazyImport.update(
  {
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardRouteRoute,
  } as any,
).lazy(() =>
  import('./routes/dashboard/settings/route.lazy').then((d) => d.Route),
)

const DashboardUsersIndexLazyRoute = DashboardUsersIndexLazyImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRouteRoute,
} as any).lazy(() =>
  import('./routes/dashboard/users/index.lazy').then((d) => d.Route),
)

const DashboardStatisticsIndexLazyRoute =
  DashboardStatisticsIndexLazyImport.update({
    id: '/statistics/',
    path: '/statistics/',
    getParentRoute: () => DashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/statistics/index.lazy').then((d) => d.Route),
  )

const DashboardSettingsIndexLazyRoute = DashboardSettingsIndexLazyImport.update(
  {
    id: '/',
    path: '/',
    getParentRoute: () => DashboardSettingsRouteLazyRoute,
  } as any,
).lazy(() =>
  import('./routes/dashboard/settings/index.lazy').then((d) => d.Route),
)

const DashboardNotificationsIndexLazyRoute =
  DashboardNotificationsIndexLazyImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => DashboardRouteRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/notifications/index.lazy').then((d) => d.Route),
  )

const DashboardLevelTwoIndexLazyRoute = DashboardLevelTwoIndexLazyImport.update(
  {
    id: '/level-two/',
    path: '/level-two/',
    getParentRoute: () => DashboardRouteRoute,
  } as any,
).lazy(() =>
  import('./routes/dashboard/level-two/index.lazy').then((d) => d.Route),
)

const DashboardLevelOneIndexLazyRoute = DashboardLevelOneIndexLazyImport.update(
  {
    id: '/level-one/',
    path: '/level-one/',
    getParentRoute: () => DashboardRouteRoute,
  } as any,
).lazy(() =>
  import('./routes/dashboard/level-one/index.lazy').then((d) => d.Route),
)

const DashboardSettingsWalletLazyRoute =
  DashboardSettingsWalletLazyImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => DashboardSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/settings/wallet.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteLazyImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/settings/wallet': {
      id: '/dashboard/settings/wallet'
      path: '/wallet'
      fullPath: '/dashboard/settings/wallet'
      preLoaderRoute: typeof DashboardSettingsWalletLazyImport
      parentRoute: typeof DashboardSettingsRouteLazyImport
    }
    '/dashboard/level-one/': {
      id: '/dashboard/level-one/'
      path: '/level-one'
      fullPath: '/dashboard/level-one'
      preLoaderRoute: typeof DashboardLevelOneIndexLazyImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/level-two/': {
      id: '/dashboard/level-two/'
      path: '/level-two'
      fullPath: '/dashboard/level-two'
      preLoaderRoute: typeof DashboardLevelTwoIndexLazyImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/notifications/': {
      id: '/dashboard/notifications/'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsIndexLazyImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexLazyImport
      parentRoute: typeof DashboardSettingsRouteLazyImport
    }
    '/dashboard/statistics/': {
      id: '/dashboard/statistics/'
      path: '/statistics'
      fullPath: '/dashboard/statistics'
      preLoaderRoute: typeof DashboardStatisticsIndexLazyImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersIndexLazyImport
      parentRoute: typeof DashboardRouteImport
    }
  }
}

// Create and export the route tree

interface DashboardSettingsRouteLazyRouteChildren {
  DashboardSettingsWalletLazyRoute: typeof DashboardSettingsWalletLazyRoute
  DashboardSettingsIndexLazyRoute: typeof DashboardSettingsIndexLazyRoute
}

const DashboardSettingsRouteLazyRouteChildren: DashboardSettingsRouteLazyRouteChildren =
  {
    DashboardSettingsWalletLazyRoute: DashboardSettingsWalletLazyRoute,
    DashboardSettingsIndexLazyRoute: DashboardSettingsIndexLazyRoute,
  }

const DashboardSettingsRouteLazyRouteWithChildren =
  DashboardSettingsRouteLazyRoute._addFileChildren(
    DashboardSettingsRouteLazyRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardSettingsRouteLazyRoute: typeof DashboardSettingsRouteLazyRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardLevelOneIndexLazyRoute: typeof DashboardLevelOneIndexLazyRoute
  DashboardLevelTwoIndexLazyRoute: typeof DashboardLevelTwoIndexLazyRoute
  DashboardNotificationsIndexLazyRoute: typeof DashboardNotificationsIndexLazyRoute
  DashboardStatisticsIndexLazyRoute: typeof DashboardStatisticsIndexLazyRoute
  DashboardUsersIndexLazyRoute: typeof DashboardUsersIndexLazyRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardSettingsRouteLazyRoute: DashboardSettingsRouteLazyRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardLevelOneIndexLazyRoute: DashboardLevelOneIndexLazyRoute,
  DashboardLevelTwoIndexLazyRoute: DashboardLevelTwoIndexLazyRoute,
  DashboardNotificationsIndexLazyRoute: DashboardNotificationsIndexLazyRoute,
  DashboardStatisticsIndexLazyRoute: DashboardStatisticsIndexLazyRoute,
  DashboardUsersIndexLazyRoute: DashboardUsersIndexLazyRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteLazyRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/settings/wallet': typeof DashboardSettingsWalletLazyRoute
  '/dashboard/level-one': typeof DashboardLevelOneIndexLazyRoute
  '/dashboard/level-two': typeof DashboardLevelTwoIndexLazyRoute
  '/dashboard/notifications': typeof DashboardNotificationsIndexLazyRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexLazyRoute
  '/dashboard/statistics': typeof DashboardStatisticsIndexLazyRoute
  '/dashboard/users': typeof DashboardUsersIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/settings/wallet': typeof DashboardSettingsWalletLazyRoute
  '/dashboard/level-one': typeof DashboardLevelOneIndexLazyRoute
  '/dashboard/level-two': typeof DashboardLevelTwoIndexLazyRoute
  '/dashboard/notifications': typeof DashboardNotificationsIndexLazyRoute
  '/dashboard/settings': typeof DashboardSettingsIndexLazyRoute
  '/dashboard/statistics': typeof DashboardStatisticsIndexLazyRoute
  '/dashboard/users': typeof DashboardUsersIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteLazyRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/settings/wallet': typeof DashboardSettingsWalletLazyRoute
  '/dashboard/level-one/': typeof DashboardLevelOneIndexLazyRoute
  '/dashboard/level-two/': typeof DashboardLevelTwoIndexLazyRoute
  '/dashboard/notifications/': typeof DashboardNotificationsIndexLazyRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexLazyRoute
  '/dashboard/statistics/': typeof DashboardStatisticsIndexLazyRoute
  '/dashboard/users/': typeof DashboardUsersIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/settings/wallet'
    | '/dashboard/level-one'
    | '/dashboard/level-two'
    | '/dashboard/notifications'
    | '/dashboard/settings/'
    | '/dashboard/statistics'
    | '/dashboard/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/settings/wallet'
    | '/dashboard/level-one'
    | '/dashboard/level-two'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/dashboard/statistics'
    | '/dashboard/users'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/settings/wallet'
    | '/dashboard/level-one/'
    | '/dashboard/level-two/'
    | '/dashboard/notifications/'
    | '/dashboard/settings/'
    | '/dashboard/statistics/'
    | '/dashboard/users/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard/route.tsx",
      "children": [
        "/dashboard/settings",
        "/dashboard/",
        "/dashboard/level-one/",
        "/dashboard/level-two/",
        "/dashboard/notifications/",
        "/dashboard/statistics/",
        "/dashboard/users/"
      ]
    },
    "/dashboard/settings": {
      "filePath": "dashboard/settings/route.lazy.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/settings/wallet",
        "/dashboard/settings/"
      ]
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/settings/wallet": {
      "filePath": "dashboard/settings/wallet.lazy.tsx",
      "parent": "/dashboard/settings"
    },
    "/dashboard/level-one/": {
      "filePath": "dashboard/level-one/index.lazy.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/level-two/": {
      "filePath": "dashboard/level-two/index.lazy.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/notifications/": {
      "filePath": "dashboard/notifications/index.lazy.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/settings/": {
      "filePath": "dashboard/settings/index.lazy.tsx",
      "parent": "/dashboard/settings"
    },
    "/dashboard/statistics/": {
      "filePath": "dashboard/statistics/index.lazy.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/users/": {
      "filePath": "dashboard/users/index.lazy.tsx",
      "parent": "/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
